removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
player forceAddUniform "VSM_G2_camo_MultiCam";
for "_i" from 1 to 2 do {player addItemToUniform "adv_aceSplint_splint";};
player addItemToUniform "ACE_morphine";
player addItemToUniform "ACE_IR_Strobe_Item";
for "_i" from 1 to 8 do {player addItemToUniform "ACE_quikclot";};
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addVest "VSM_LBT6094_gen2_556";
for "_i" from 1 to 2 do {player addItemToVest "16Rnd_9x21_Mag";};
for "_i" from 1 to 5 do {player addItemToVest "SMA_30Rnd_556x45_M855A1";};
for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_M84";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_Chemlight_HiYellow";};
player addHeadgear "milgp_h_opscore_01_RGR";
player addItemToUniform "A3_GPNVG18_F";
player addWeapon "SMA_Mk16_black";
player addPrimaryWeaponItem "SMA_supp2BW_556";
player addWeapon "hgun_Rook40_F";
player linkItem "TFAR_microdagr";
player linkItem "TFAR_anprc152";