removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
player forceAddUniform "U_B_Wetsuit";
player addVest "V_RebreatherB";
player addBackpack "GSRI_backpack_A";
for "_i" from 1 to 2 do {player addItemToBackpack "adv_aceSplint_splint";};
player addItemToBackpack "ACE_morphine";
player addItemToBackpack "ACE_IR_Strobe_Item";
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_quikclot";};
player addItemToBackpack "ACE_EarPlugs";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_CableTie";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_tourniquet";};
player addItemToBackpack "A3_GPNVG18_F";
player addItemToBackpack "VSM_G2_camo_MultiCam";
player addItemToBackpack "VSM_LBT6094_gen2_556";
player addItemToBackpack "16Rnd_9x21_Mag";
for "_i" from 1 to 4 do {player addItemToBackpack "SMA_30Rnd_556x45_M855A1";};
for "_i" from 1 to 2 do {player addItemToBackpack "HandGrenade";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShell";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_M84";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiYellow";};
player addHeadgear "milgp_h_opscore_01_RGR";
player addGoggles "G_B_Diving";
player addWeapon "SMA_Mk16_black";
player addPrimaryWeaponItem "SMA_supp2BW_556";
player addWeapon "hgun_Rook40_F";
player linkItem "TFAR_microdagr";
player linkItem "TFAR_anprc152";