removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
player forceAddUniform "VSM_G2_camo_MultiCam";
for "_i" from 1 to 2 do {player addItemToUniform "adv_aceSplint_splint";};
player addItemToUniform "ACE_morphine";
player addItemToUniform "ACE_IR_Strobe_Item";
for "_i" from 1 to 8 do {player addItemToUniform "ACE_quikclot";};
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "A3_GPNVG18_F";
player addVest "6094_MEDIC_od";
player addItemToVest "ACE_surgicalKit";
player addItemToVest "ACE_personalAidKit";
player addItemToVest "adv_aceCPR_AED";
for "_i" from 1 to 6 do {player addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_Chemlight_HiYellow";};
for "_i" from 1 to 4 do {player addItemToVest "SMA_30Rnd_556x45_M855A1";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShellYellow";};
player addBackpack "GSRI_backpack_B_medic";
for "_i" from 1 to 10 do {player addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {player addItemToBackpack "adv_aceSplint_splint";};
for "_i" from 1 to 15 do {player addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 30 do {player addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV";};
player addHeadgear "milgp_h_opscore_01_RGR";
player addWeapon "SMA_Mk16_blackQCB";
player addPrimaryWeaponItem "SMA_supp2BW_556";
player linkItem "TFAR_microdagr";
player linkItem "TFAR_anprc152";