name: release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: ['addons/**']

jobs:
  release:
    runs-on: [self-hosted, arma-tools]
    steps:

      - name: Checkout files
        uses: actions/checkout@v3

      - name: Build opex addon
        uses: team-gsri/actions-arma-tools/build-addon@v0
        with:
          prefix: 'fr\gsri\opex'
          source: ./addons/gsri_opex
          target: ./
          
      - name: Build units addon
        uses: team-gsri/actions-arma-tools/build-addon@v0
        with:
          prefix: 'fr\gsri\units'
          source: ./addons/gsri_units
          target: ./
          
      - name: Upload pbo files
        uses: actions/upload-artifact@v3
        with:
          name: addons
          path: ./*.pbo

      - name: Create Github release
        uses: arwynfr/actions-conventional-versioning@v0
        with:
          pattern: $(Convert-Path *.pbo)
